name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f Dockerfile --output package . --tag ffmime:$(date +%s)
    - name: Commit files
      run: |
        git config --local user.email "wan.junjie@foxmail.com"
        git config --local user.name "GAbot"
        git add ./package
        git commit -m "rebuild wasm"
    - name: push to codebase
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
